repos:
  # -------- Hygiene básica --------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  # -------- Segurança: detect-secrets --------
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: '(^docs/.*$|^README\.md$|^internal/sockets/messagery/rabbitmq\.go$)'
        files: '^(.*\.go$|.*\.yaml$|.*\.yml$|.*\.json$|.*\.tf$|.*\.tfvars$|.*\.sh$|.*\.ps1$)'

  # -------- Segurança: gitleaks --------
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks
        language: system
        pass_filenames: false
        args:
          [
            "protect",
            "--staged",
            "--no-banner",
            "--config=support/.gitleaks.toml",
          ]

  # -------- Go tools --------
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-mod-tidy
        # - id: golangci-lint
        # args: ["run", "--config=./support/.golangci.yaml"]
